seed: /home/user/Desktop/Thesis/Masterproef-paper/code/examples/metamorphic/knights_path16650534694640708
solver: minizinc:cp
metaRelations: ['==1', 'True->cons', 'addZero2Sum', 'sementicFusion*']
error reason: syntax error, unexpected +, expecting identifier
error trace: Traceback (most recent call last):
  File "metamorphic.py", line 479, in __main__
    mmodel.modifModel.solve(solver=mmodel.solver, time_limit=timeout)
  File "/usr/local/lib/python3.8/dist-packages/cpmpy-0.9.9-py3.8.egg/cpmpy/model.py", line 140, in solve
    ret = s.solve(time_limit=time_limit)
  File "/usr/local/lib/python3.8/dist-packages/cpmpy-0.9.9-py3.8.egg/cpmpy/solvers/minizinc.py", line 163, in solve
    (mzn_kwargs, mzn_inst) = self._pre_solve(time_limit=time_limit, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/cpmpy-0.9.9-py3.8.egg/cpmpy/solvers/minizinc.py", line 138, in _pre_solve
    mzn_inst = minizinc.Instance(self.mzn_solver, copy_model)
  File "/home/user/.local/lib/python3.8/site-packages/minizinc/instance.py", line 100, in __init__
    self.analyse()
  File "/home/user/.local/lib/python3.8/site-packages/minizinc/instance.py", line 599, in analyse
    output = self._driver._run(["--model-interface-only"] + files, self._solver)
  File "/home/user/.local/lib/python3.8/site-packages/minizinc/driver.py", line 232, in _run
    for _ in decode_json_stream(output.stdout):
  File "/home/user/.local/lib/python3.8/site-packages/minizinc/json.py", line 89, in decode_json_stream
    raise error_from_stream_obj(obj)
minizinc.error.SyntaxError: syntax error, unexpected +, expecting identifier

