solveAll
seed: /home/user/Desktop/Thesis/Masterproef-paper/code/examples/forDiffTesting/exodus16650527724432807
solver: minizinc:chuffed
error reason: MiniZinc solver returned with status 'Error'
error trace: Traceback (most recent call last):
  File "differentialTesting.py", line 140, in differentialTest
    sol = m.solveAll(solver=solver, time_limit=timeout, solution_limit=100)
  File "/usr/local/lib/python3.8/dist-packages/cpmpy-0.9.9-py3.8.egg/cpmpy/model.py", line 165, in solveAll
    ret = s.solveAll(display=display,time_limit=time_limit,solution_limit=solution_limit)
  File "/usr/local/lib/python3.8/dist-packages/cpmpy-0.9.9-py3.8.egg/cpmpy/solvers/minizinc.py", line 496, in solveAll
    return asyncio.run(coroutine)
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/cpmpy-0.9.9-py3.8.egg/cpmpy/solvers/minizinc.py", line 267, in _solveAll
    self._post_solve(mzn_result)
  File "/usr/local/lib/python3.8/dist-packages/cpmpy-0.9.9-py3.8.egg/cpmpy/solvers/minizinc.py", line 216, in _post_solve
    raise Exception("MiniZinc solver returned with status 'Error'")
Exception: MiniZinc solver returned with status 'Error'

